[
  "--remote-debugging-port=9222",
  "--disable-background-networking",
  "--disable-extensions",
  "--disable-component-update",
  "--disable-client-side-phishing-detection",
  "--metrics-recording-only",
  "--disable-default-apps",
  "--no-default-browser-check",
  "--no-first-run",
  "--force-fieldtrials=*BackgroundTracing/default/"
]
